---
title: "BZN PSA"
author: "Philip Wikman"
date: "2025-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Paquetes necesarios
library(dplyr)
library(ggplot2)
library(MASS)
library(tidyr)
library(ggplot2)
source("calculate_qalys_costs.R")
source("Simulate.R")
source("Simulate_t.R")
source("QalyCost.R")
source("invbeta.R")
source("generate_rr_lognormal.R")
```


```{r}
# Definir parámetros del modelo
cycle_length <- 1        # Longitud de cada ciclo (en años)
discount_rate <- 0.03    # Tasa de descuento anual
BestVariab<-as.numeric(as.vector(readRDS("BestVariab_100000.RDS")))
grupos_sexo<-c("Hombre", "Mujer")
states <- c("Chronic_Asymptomatic", "Cardiac", "Digestive", "Death")
grupos_edad<-c("15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69")
# Estados de salud

P_card<-BestVariab[1]
CaMorR<-BestVariab[2]
DiMorR<-BestVariab[3] # Cucunubá et al. Parasites&Vectors 2016
P_card_t<-BestVariab[1]*0.49
P_dig<-BestVariab[4]
P_dig_t<-BestVariab[4]*0.88

P_mort_m<-c(0.00015, 0.00037, 0.00044, 0.00054, 0.00077, 0.00095, 0.00161, 0.00289, 0.00543, 0.00893, 0.01401)
P_mort_W<-c(0.00014, 0.00016, 0.00015, 0.00023, 0.00037, 0.00062, 0.00096, 0.00158, 0.00273, 0.00429, 0.00648)

qaly_weights <- c(
  Chronic_Asymptomatic = 0.9625,
  Cardiac = 0.7171,
  Digestive = 0.80,
  Death = 0
)

costs <- c(
  Chronic_Asymptomatic = 478,
  Cardiac = 11976.53,
  Digestive = 858.82,
  Death = 0
)

discount_rate <- 0.03  # 3% discount rate
repeats<-1000
ParameterDat<-data.frame(matrix(NA, nrow=repeats, ncol=6))
PSADAT<-matrix(NA, nrow=repeats, ncol=3)
colnames(PSADAT)<-c("AQALYs", "ACosts", "ICER")
set.seed(123)
```
# Selection of parameters
```{r}

  
  P_card<-invbeta(mu=0.0076, low=0.013, high=0.03, n=repeats)
  CaMorR<-generate_rr_lognormal(1.1,3,1.57, n=repeats)
  DiMorR<-generate_rr_lognormal(0.9,1.5, 1, n=repeats)
  P_dig<-invbeta(mu=0.027, low=0.008, high=0.035, n=repeats)
  RR_T_car<-generate_rr_lognormal(0.19,1.25,0.49, n=repeats)
  RR_T_dig<-generate_rr_lognormal(0.55,1.42,0.88, n=repeats)
  
for (i in 1:repeats){ 
  ParameterDat[i,1]<-P_card[i]
  ParameterDat[i,2]<-CaMorR[i]
  ParameterDat[i,3]<-DiMorR[i]
  ParameterDat[i,4]<-P_dig[i]
  ParameterDat[i,5]<-RR_T_car[i]
  ParameterDat[i,6]<-RR_T_dig[i]
}
```


# PSA analysis
```{r}

for (i in 1:repeats){
### Simulating non-treatment arm
population_over_time<-Simulate(P_card=P_card[i], CaMorR=CaMorR[i], DiMorR=DiMorR[i], P_dig=P_dig[i], horizon=20)

### Simulating the treatment arm

population_over_time_t<-Simulate_t(P_card=P_card[i], CaMorR=CaMorR[i], DiMorR=DiMorR[i], P_dig=P_dig[i], RR_T_car=RR_T_car[i], RR_T_dig=RR_T_dig[i], horizon=20)


# Calculate Qalys and costs 
Det_CEA_H<-QalyCost(population_over_time, population_over_time_t)
PSADAT[i,]<-as.numeric(Det_CEA_H[2,4:6])

# Progresion counter
cat(sprintf("\rProgress: %d%% | Iteration %d of %d", round(i / repeats * 100), i, repeats))
    flush.console()
}
# Convert PSADAT to a data frame
PSADAT_df <- as.data.frame(PSADAT)
```
```{r}
summary(PSADAT_df$ICER)
quantile(PSADAT_df$ICER,c(0.05,0.95))
```

```{r}
library(ggplot2)

ggplot(PSADAT_df, aes(x = AQALYs, y = ACosts)) +
  geom_point(color = "blue", alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey40") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey40") +
  labs(
    title = "Cost-Effectiveness Plane",
    x = expression(Delta~"QALYs"),
    y = expression(Delta~"Costs (2023€)")
  ) +
  stat_ellipse()
  theme_minimal()

```

```{r}
# Define WTP thresholds
wtp <- seq(-150000, 30000, by = 500)

# For each WTP, calculate probability intervention is cost-effective
ce_prob <- sapply(wtp, function(w) {
  mean(PSADAT_df$ACosts < w * PSADAT_df$AQALYs)
})

# Create data frame for plotting
ceac_data <- data.frame(
  WTP = wtp,
  CE_Probability = ce_prob
)

# Plot CEAC
ggplot(ceac_data, aes(x = WTP, y = CE_Probability)) +
  geom_line(color = "darkgreen", linewidth = 1) +
  ylim(0,1) +
  labs(
    title = "Cost-Effectiveness Acceptability Curve (CEAC)",
    x = "Willingness-to-pay Threshold (€ per QALY)",
    y = "Probability Cost-Effective"
  ) +
  theme_minimal()
```