---
title: "BZN CEA"
author: "Philip Wikman"
date: "2025-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Paquetes necesarios
library(dplyr)
library(ggplot2)
library(MASS)
library(tidyr)
source("calculate_qalys_costs.R")
source("Simulate.R")
source("Simulate_t.R")
variab_df<-readRDS("variab_df.RDS")
reps_SMSE<-readRDS("reps_SMSE.rds")
```


```{r}
# Definir parámetros del modelo
cycle_length <- 1        # Longitud de cada ciclo (en años)
discount_rate <- 0.03    # Tasa de descuento anual

# Estados de salud
x<-which.min(reps_SMSE)

P_card<-variab_df[x, "P_card_v"]
CaMorR<-variab_df[x, "CaMorR_v"]
DiMorR<-variab_df[x, "DiMorR_v"] # Cucunubá et al. Parasites&Vectors 2016
P_card_t<-variab_df[x, "P_card_v"]*0.54
P_dig<-variab_df[x, "P_dig_v"]
P_dig_t<-variab_df[x, "P_dig_v"]*0.90

P_mort_m<-c(0.00015, 0.00037, 0.00044, 0.00054, 0.00077, 0.00095, 0.00161, 0.00289, 0.00543, 0.00893, 0.01401)
P_mort_W<-c(0.00014, 0.00016, 0.00015, 0.00023, 0.00037, 0.00062, 0.00096, 0.00158, 0.00273, 0.00429, 0.00648)

population_over_time<-Simulate(P_card=P_card, CaMorR=CaMorR, DiMorR=DiMorR, P_dig=P_dig, horizon=20)
```
## Ploting evolution over time of non treatment arm
```{r}

# Convert list to a long-format data frame
df <- data.frame()
horizon=20
for (t in 1:horizon) {
  for (sex in grupos_sexo) {
    for (age in grupos_edad) {
      state_values <- population_over_time[[t]][[sex]][[age]]
      df <- rbind(df, data.frame(
        Year = t,
        Sex = sex,
        Age_Group = age,
        Chronic_Asymptomatic = state_values[1],
        Cardiac = state_values[2],
        Digestive = state_values[3],
        Death = state_values[4]
      ))
    }
  }
}

# Convert data to long format for ggplot
df_long <- df %>%
  pivot_longer(cols = c("Chronic_Asymptomatic", "Cardiac", "Digestive", "Death"),
               names_to = "State",
               values_to = "Count")

# Ensure ordered age groups (optional)
df_long$Age_Group <- factor(df_long$Age_Group, levels = grupos_edad)

ggplot(df_long, aes(x = Year, y = Count, fill = State)) +
  geom_col(position="stack",alpha = 0.6) +  # Stacked area plot
  #geom_smooth(aes(group = State), method = "loess", color = "black", size = 0.5, se = FALSE) +
  facet_wrap(~Sex+Age_Group, scales = "free_y") +  # Facet by Sex and Age Group
  labs(
    title = "Evolution of Health States Over Time",
    x = "Year",
    y = "Number of Individuals",
    fill = "Health State"
  ) +
  theme_minimal()

```


# Simulating the treatment arm

```{r}
population_over_time_t<-Simulate_t(P_card=P_card, CaMorR=CaMorR, DiMorR=DiMorR, P_dig=P_dig, RR_T_car=0.49, RR_T_dig=0.88, horizon=20)

```

## Ploting evolution over time of treatment arm
```{r}

# Convert list to a long-format data frame
df_t <- data.frame()

for (t in 1:horizon) {
  for (sex in grupos_sexo) {
    for (age in grupos_edad) {
      state_values <- population_over_time_t[[t]][[sex]][[age]]
      df_t <- rbind(df_t, data.frame(
        Year = t,
        Sex = sex,
        Age_Group = age,
        Chronic_Asymptomatic = state_values[1],
        Cardiac = state_values[2],
        Digestive = state_values[3],
        Death = state_values[4]
      ))
    }
  }
}

# Convert data to long format for ggplot
df_long <- df_t %>%
  pivot_longer(cols = c("Chronic_Asymptomatic", "Cardiac", "Digestive", "Death"),
               names_to = "State",
               values_to = "Count")

# Ensure ordered age groups (optional)
df_long$Age_Group <- factor(df_long$Age_Group, levels = grupos_edad)

ggplot(df_long, aes(x = Year, y = Count, fill = State)) +
  geom_col(position="stack", alpha = 0.6) +  # Stacked area plot
  #geom_smooth(aes(group = State), method = "loess", color = "black", size = 0.5, se = FALSE) +
  facet_wrap(~Sex+Age_Group, scales = "free_y") +  # Facet by Sex and Age Group
  labs(
    title = "Evolution of Health States Over Time",
    x = "Year",
    y = "Number of Individuals",
    fill = "Health State"
  ) +
  theme_minimal()

```


# Calculate Qalys and costs of non treatment arm

```{r}
qaly_weights <- c(
  Chronic_Asymptomatic = 0.9625,
  Cardiac = 0.7171,
  Digestive = 0.60,
  Death = 0
)

costs <- c(
  Chronic_Asymptomatic = 500,
  Cardiac = 10000,
  Digestive = 5000,
  Death = 0
)

discount_rate <- 0.03  # 3% discount rate


# Compute QALYs and costs
qalys_costs_results <- calculate_qalys_costs(population_over_time, qaly_weights, costs, discount_rate)

# Print results
No_treat<-colSums(qalys_costs_results[,2:3])
No_treat
```
# Calculate QALYs and costs of treatment arm
```{r}
# Compute QALYs and costs
qalys_costs_results_t <- calculate_qalys_costs(population_over_time_t, qaly_weights, costs, discount_rate)

# Print results
treat<-colSums(qalys_costs_results_t[,2:3])
treat
```

```{r}
Det_CEA<-bind_rows(No_treat, treat)%>%mutate(Intervention=c("No treatment", "Benznidazole")) 
Det_CEA$Intervention<-as.factor(Det_CEA$Intervention)                                            
ACost=Det_CEA$Costs[2]-Det_CEA$Costs[1]
AQALYs=Det_CEA$QALYs[2]-Det_CEA$QALYs[1]
ICER=ACost/AQALYs
ACost
AQALYs
ICER
a<-1
b<-1
Det_CEA$AQALYs<-c(a, AQALYs)
Det_CEA$ACosts<-c(b, ACost)
```


```{r}
ggplot(Det_CEA, aes(x=AQALYs, y=ACosts, fill=Intervention))+
  geom_point(size = 4, shape = 21)+
  #ylim(-100000000,100000)+
  #scale_y_log10()+
  geom_hline(yintercept =0)+
  geom_vline(xintercept =0)+
  #xlim(-200,3000)+
  theme_minimal()+
  ggtitle("Cost-effectivenes plane of Benznidazole 
          vs no treatment")
```