---
title: "BZN CEA"
author: "Philip Wikman"
date: "2025-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Paquetes necesarios
library(dplyr)
library(ggplot2)
library(MASS)
library(tidyr)

source("invbeta.R")
source("generate_rr_lognormal.R")
```


```{r}
set.seed(123)

reps<-100
reps_SMSE<-vector(mode="numeric", length=length(reps))
  

P_card_v<-invbeta(mu=0.019, low=0.013, high=0.03, n=reps)
CaMorR_v<-generate_rr_lognormal(2,12,n=reps)
DiMorR_v<-generate_rr_lognormal(0.9,2,n=reps)
P_dig_v<-invbeta(mu=0.011, low=0.008, high=0.0136, n=reps)

for (i in 1:reps){
cat(sprintf("\rProgress: %d%% | Iteration %d of %d", round(i / reps * 100), i, reps))
flush.console()

# Definir parámetros del modelo
horizon <- 5           # Horizonte temporal (en años)
cycle_length <- 1        # Longitud de cada ciclo (en años)

# Estados de salud
states <- c("Chronic_Asymptomatic", "Cardiac", "Digestive", "Death")
grupos_edad<-c("15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69")
grupos_sexo<-c("Hombre", "Mujer")
deaths<-c(3,0,7,5,9)#4,2,4,5,6,
years<-c(2014:2018)

P_card<-P_card_v[i]
CaMorR<-CaMorR_v[i]
DiMorR<-DiMorR_v[i] #(1.5-2.91) # Cucunubá et al. Parasites&Vectors 2016
#P_card_t<-0.019*0.491.5
P_dig<-P_dig_v[i]
#P_dig_t<-0.011*0.88

P_mort_m<-c(0.00015, 0.00037, 0.00044, 0.00054, 0.00077, 0.00095, 0.00161, 0.00289, 0.00543, 0.00893, 0.01401)
P_mort_W<-c(0.00014, 0.00016, 0.00015, 0.00023, 0.00037, 0.00062, 0.00096, 0.00158, 0.00273, 0.00429, 0.00648)

# Probabilidades de transición para el brazo SIN intervención
transition_matrices <- list(
  "Hombre" = list(
    "15-19" = matrix(c(1-P_card-P_dig-P_mort_m[1], P_card, P_dig, P_mort_m[1],  
                       0.00, 1-P_dig-P_mort_m[1]*CaMorR, P_dig, P_mort_m[1]*CaMorR,  
                       0.00, P_card, 1-P_mort_m[1]*DiMorR, P_mort_m[1]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4),

    "20-24" = matrix(c(1-P_card-P_dig-P_mort_m[2], P_card, P_dig, P_mort_m[2],  
                       0.00, 1-P_dig-P_mort_m[2]*CaMorR, P_dig, P_mort_m[2]*CaMorR, 
                       0.00, P_card, 1-P_mort_m[2]*DiMorR, P_mort_m[2]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4),

    "25-29" = matrix(c(1-P_card-P_dig-P_mort_m[3], P_card, P_dig, P_mort_m[3],  
                       0.00, 1-P_dig-P_mort_m[3]*CaMorR, P_dig, P_mort_m[3]*CaMorR, 
                       0.00, P_card, 1-P_mort_m[3]*DiMorR, P_mort_m[3]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4),

    "30-34" = matrix(c(1-P_card-P_dig-P_mort_m[4], P_card, P_dig, P_mort_m[4],  
                       0.00, 1-P_dig-P_mort_m[4]*CaMorR, P_dig, P_mort_m[4]*CaMorR,  
                       0.00, P_card, 1-P_mort_m[4]*DiMorR, P_mort_m[4]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4), 
    
    "35-39" = matrix(c(1-P_card-P_dig-P_mort_m[5], P_card, P_dig, P_mort_m[5],  
                       0.00, 1-P_dig-P_mort_m[5]*CaMorR, P_dig, P_mort_m[5]*CaMorR, 
                       0.00, P_card, 1-P_mort_m[5]*DiMorR, P_mort_m[5]*DiMorR, 
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4),

    "40-44" = matrix(c(1-P_card-P_dig-P_mort_m[6], P_card, P_dig, P_mort_m[6],  
                       0.00, 1-P_dig-P_mort_m[6]*CaMorR, P_dig, P_mort_m[6]*CaMorR,
                       0.00, P_card, 1-P_mort_m[6]*DiMorR, P_mort_m[6]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                    byrow = TRUE, nrow = 4),

    "45-49" = matrix(c(1-P_card-P_dig-P_mort_m[7], P_card, P_dig, P_mort_m[7],  
                       0.00, 1-P_dig-P_mort_m[7]*CaMorR, P_dig, P_mort_m[7]*CaMorR, 
                       0.00, P_card, 1-P_mort_m[7]*DiMorR, P_mort_m[7]*DiMorR,
                       0.00, 0.00, 0.00, 1.00),  
                    byrow = TRUE, nrow = 4),

    "50-54" = matrix(c(1-P_card-P_dig-P_mort_m[8], P_card, P_dig, P_mort_m[8],  
                       0.00, 1-P_dig-P_mort_m[8]*CaMorR, P_dig, P_mort_m[8]*CaMorR,  
                       0.00, P_card, 1-P_mort_m[8]*DiMorR, P_mort_m[8]*DiMorR, 
                       0.00, 0.00, 0.00, 1.00), 
                   byrow = TRUE, nrow = 4),
    
    "55-59" = matrix(c(1-P_card-P_dig-P_mort_m[9], P_card, P_dig, P_mort_m[9],  
                       0.00, 1-P_dig-P_mort_m[9]*CaMorR, P_dig, P_mort_m[9]*CaMorR,  
                       0.00, P_card, 1-P_mort_m[9]*DiMorR, P_mort_m[9]*DiMorR, 
                       0.00, 0.00, 0.00, 1.00),
                   byrow = TRUE, nrow = 4),
    
    "60-64" = matrix(c(1-P_card-P_dig-P_mort_m[10], P_card, P_dig, P_mort_m[10],  
                       0.00, 1-P_dig-P_mort_m[10]*CaMorR, P_dig, P_mort_m[10]*CaMorR, 
                       0.00, P_card, 1-P_mort_m[10]*DiMorR, P_mort_m[10]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00), 
                   byrow = TRUE, nrow = 4),
    
    "65-69" = matrix(c(1-P_card-P_dig-P_mort_m[11], P_card, P_dig, P_mort_m[11],  
                       0.00, 1-P_dig-P_mort_m[11]*CaMorR, P_dig, P_mort_m[11]*CaMorR,  
                       0.00, P_card, 1-P_mort_m[11]*DiMorR, P_mort_m[11]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4)
    
  ),
  "Mujer" = list(
        "15-19" = matrix(c(1-P_card-P_dig-P_mort_W[1], P_card, P_dig, P_mort_W[1],  
                       0.00, 1-P_dig-P_mort_W[1]*CaMorR, P_dig, P_mort_W[1]*CaMorR,  
                       0.00, P_card, 1-P_mort_W[1]*DiMorR, P_mort_W[1]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4),

    "20-24" = matrix(c(1-P_card-P_dig-P_mort_W[2], P_card, P_dig, P_mort_W[2],  
                       0.00, 1-P_dig-P_mort_W[2]*CaMorR, P_dig, P_mort_W[2]*CaMorR, 
                       0.00, P_card, 1-P_mort_W[2]*DiMorR, P_mort_W[2]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4),

    "25-29" = matrix(c(1-P_card-P_dig-P_mort_W[3], P_card, P_dig, P_mort_W[3],  
                       0.00, 1-P_dig-P_mort_W[3]*CaMorR, P_dig, P_mort_W[3]*CaMorR, 
                       0.00, P_card, 1-P_mort_W[3]*DiMorR, P_mort_W[3]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4),

    "30-34" = matrix(c(1-P_card-P_dig-P_mort_W[4], P_card, P_dig, P_mort_W[4],  
                       0.00, 1-P_dig-P_mort_W[4]*CaMorR, P_dig, P_mort_W[4]*CaMorR,  
                       0.00, P_card, 1-P_mort_W[4]*DiMorR, P_mort_W[4]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4), 
    
    "35-39" = matrix(c(1-P_card-P_dig-P_mort_W[5], P_card, P_dig, P_mort_W[5],  
                       0.00, 1-P_dig-P_mort_W[5]*CaMorR, P_dig, P_mort_W[5]*CaMorR, 
                       0.00, P_card, 1-P_mort_W[5]*DiMorR, P_mort_W[5]*DiMorR, 
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4),

    "40-44" = matrix(c(1-P_card-P_dig-P_mort_W[6], P_card, P_dig, P_mort_W[6],  
                       0.00, 1-P_dig-P_mort_W[6]*CaMorR, P_dig, P_mort_W[6]*CaMorR,
                       0.00, P_card, 1-P_mort_W[6]*DiMorR, P_mort_W[6]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                    byrow = TRUE, nrow = 4),

    "45-49" = matrix(c(1-P_card-P_dig-P_mort_W[7], P_card, P_dig, P_mort_W[7],  
                       0.00, 1-P_dig-P_mort_W[7]*CaMorR, P_dig, P_mort_W[7]*CaMorR, 
                       0.00, P_card, 1-P_mort_W[7]*DiMorR, P_mort_W[7]*DiMorR,
                       0.00, 0.00, 0.00, 1.00),  
                    byrow = TRUE, nrow = 4),

    "50-54" = matrix(c(1-P_card-P_dig-P_mort_W[8], P_card, P_dig, P_mort_W[8],  
                       0.00, 1-P_dig-P_mort_W[8]*CaMorR, P_dig, P_mort_W[8]*CaMorR,  
                       0.00, P_card, 1-P_mort_W[8]*DiMorR, P_mort_W[8]*DiMorR, 
                       0.00, 0.00, 0.00, 1.00), 
                   byrow = TRUE, nrow = 4),
    
    "55-59" = matrix(c(1-P_card-P_dig-P_mort_W[9], P_card, P_dig, P_mort_W[9],  
                       0.00, 1-P_dig-P_mort_W[9]*CaMorR, P_dig, P_mort_W[9]*CaMorR,  
                       0.00, P_card, 1-P_mort_W[9]*DiMorR, P_mort_W[9]*DiMorR, 
                       0.00, 0.00, 0.00, 1.00),
                   byrow = TRUE, nrow = 4),
    
    "60-64" = matrix(c(1-P_card-P_dig-P_mort_W[10], P_card, P_dig, P_mort_W[10],  
                       0.00, 1-P_dig-P_mort_W[10]*CaMorR, P_dig, P_mort_W[10]*CaMorR, 
                       0.00, P_card, 1-P_mort_W[10]*DiMorR, P_mort_W[10]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00), 
                   byrow = TRUE, nrow = 4),
    
    "65-69" = matrix(c(1-P_card-P_dig-P_mort_W[11], P_card, P_dig, P_mort_W[11],  
                       0.00, 1-P_dig-P_mort_W[11]*CaMorR, P_dig, P_mort_W[11]*CaMorR,  
                       0.00, P_card, 1-P_mort_W[11]*DiMorR, P_mort_W[11]*DiMorR,  
                       0.00, 0.00, 0.00, 1.00),  
                   byrow = TRUE, nrow = 4)
  )
)


# Initial population distribution (Distribución según INE (personas de sudamérica), casos según Navarro et al 2022)
population <- list()
Chr_Asym_H<-c(1624, 2767, 3867, 4136, 3554, 3166, 2292, 1496, 933, 552, 307)
names(Chr_Asym_H)<-grupos_edad
  for (age  in grupos_edad) {
    population[["Hombre"]][[age]] <- c(Chronic_Asymptomatic = Chr_Asym_H[age], 
                                   Cardiac = 0, 
                                   Digestive = 0, 
                                   Death = 0)
  }

Chr_Asym_M<-c(1355, 2571, 4170, 4378, 4053, 3861, 3091, 2521, 1939, 1369, 1014)
names(Chr_Asym_M)<-grupos_edad
  for (age  in grupos_edad) {
    population[["Mujer"]][[age]] <- c(Chronic_Asymptomatic = Chr_Asym_M[age], 
                                   Cardiac = 0, 
                                   Digestive = 0, 
                                   Death = 0)
  }

# Simulation loop

# Initialize storage for population evolution
population_over_time <- list()
deaths_chagas_over_time <- list()

prop_moving <- 0.2  # 20% of the population moves each year as the year groups are of 5 years
for (t in 1:horizon) {
  
  new_population <- list()
  deaths_chagas <- list()
  
  for (sex in grupos_sexo) {
    new_population[[sex]] <- list()
    deaths_chagas[[sex]] <- list()
    
    for (age in grupos_edad) {
      new_population[[sex]][[age]] <- rep(0, length(states)) # Initialize empty state vector
      deaths_chagas[[sex]][[age]] <- 0 # Initialize Chagas deaths
    }
  }
  
  total_deaths <- 0  # To accumulate deaths during this cycle
  
  for (sex in grupos_sexo) {
    for (age in grupos_edad) {
      # Get the transition matrix
        trans_mat <- matrix(as.numeric(transition_matrices[[sex]][[age]]), nrow = 4, ncol = 4)
      
        # Current population in this (sex, age) group
        current_pop <- unlist(population[[sex]][[age]])
        current_pop<-matrix(as.numeric(current_pop), nrow = 1)
        # Compute next year's population distribution
        
        # Split population into those who stay and those who move to next age group
      moving_out <- prop_moving * current_pop
      staying <- (1 - prop_moving) * current_pop

      # Apply transitions separately
      moved_pop <- as.numeric(moving_out %*% trans_mat)
      stayed_pop <- as.numeric(staying %*% trans_mat)
      
      # Count all deaths
      death_index <- which(states == "Death")
      deaths_from_group <- sum(moved_pop[death_index]) + sum(stayed_pop[death_index])
      total_deaths <- total_deaths + deaths_from_group

      # Remove deaths
      # moved_pop[death_index] <- 0
      # stayed_pop[death_index] <- 0

      # Calculate Chagas deaths
      cardiac_chagas_index <- which(states == "Cardiac")
      deaths_from_cardiac_chagas <- current_pop[cardiac_chagas_index] * trans_mat[cardiac_chagas_index, death_index]
      deaths_chagas[[sex]][[age]] <- (1 - (1 / CaMorR)) * deaths_from_cardiac_chagas

      # Move individuals to the next age group if possible
      next_age_group <- switch(age,
                               "15-19" = "20-24",
                               "20-24" = "25-29",
                               "25-29" = "30-34",
                               "30-34" = "35-39",
                               "35-39" = "40-44",
                               "40-44" = "45-49",
                               "45-49" = "50-54",
                               "50-54" = "55-59",
                               "55-59" = "60-64",
                               "60-64" = "65-69",
                               "65-69" = "70-74",
                               age  # If the age group is not in the switch statement, keep it
      )

     # Store updated population
      if (next_age_group != age) {
        new_population[[sex]][[next_age_group]] <- new_population[[sex]][[next_age_group]] + moved_pop
      }

      new_population[[sex]][[age]] <- new_population[[sex]][[age]] + stayed_pop
    }
  }
  
  # Inject newborns into 15–19 group, Chronic_Asymptomatic state
  #start_state_index <- which(states == "Chronic_Asymptomatic")
  #for (sex in grupos_sexo) {
  #  new_population[[sex]][["15-19"]][start_state_index] <-
  #    new_population[[sex]][["15-19"]][start_state_index] + total_deaths / #length(grupos_sexo)
 # }

  # Save population state at this time step
  population_over_time[[t]] <- new_population
  deaths_chagas_over_time[[t]] <- deaths_chagas

  # Update population for the next cycle
  population <- new_population
}

df <- data.frame()

for (t in 1:horizon) {
  for (sex in grupos_sexo) {
    for (age in grupos_edad) {
      state_values <- population_over_time[[t]][[sex]][[age]]
      df <- rbind(df, data.frame(
        Year = t,
        Sex = sex,
        Age_Group = age,
        Chronic_Asymptomatic = state_values[1],
        Cardiac = state_values[2],
        Digestive = state_values[3],
        Death = state_values[4]
      ))
    }
  }
}

deaths_chagas_df <- do.call(rbind, lapply(seq_along(deaths_chagas_over_time), function(t) {
  data <- deaths_chagas_over_time[[t]]
  do.call(rbind, lapply(names(data), function(sex) {
    do.call(rbind, lapply(names(data[[sex]]), function(age) {
      data.frame(
        year = t,
        sex = sex,
        age_group = age,
        deaths = data[[sex]][[age]]
      )
    }))
  }))
}))

deaths_chagas_disease <- deaths_chagas_df%>%group_by(year)%>%summarise(count=sum(deaths, na.rm=TRUE))%>%
  mutate(year=2014:2018)
deaths_chagas_disease2<-cbind(deaths_chagas_disease, deaths)

MSE<-(deaths_chagas_disease2$deaths-deaths_chagas_disease2$count)^2
MSE
SMSE<-sum(MSE)/length(MSE)
SMSE

#reps_SMSE[i]<-SMSE
#reps_SMSE
#### Fitting Digestive Chagas disease to 10% prevalence

digestive_chagas_df <- do.call(rbind, lapply(seq_along(population_over_time), function(t) {
  data <- population_over_time[[t]]
  do.call(rbind, lapply(names(data), function(sex) {
    do.call(rbind, lapply(names(data[[sex]]), function(age) {
      data.frame(
        year = t,
        sex = sex,
        age_group = age,
        digestive = data[[sex]][[age]][3],
        total=sum(data[[sex]][[age]])
      )
    }))
  }))
}))


digestive_chagas_disease <- digestive_chagas_df%>%group_by(year)%>%summarise(count=sum(digestive, na.rm=TRUE), total=sum(total))%>%mutate(prop=count/total, year=2014:2018)

### Falta calcular la referencia con la que ajustar la prevalencia de patología digestiva.
digestive_prev<-0.1

MSE_dig<-(digestive_chagas_disease$prop[1:5]-digestive_prev)^2
MSE_dig
SMSE_dig<-sum(MSE_dig)/length(MSE_dig)
SMSE_dig

reps_SMSE[i]<-100000*SMSE_dig+SMSE
}
reps_SMSE
```
```{r}
variab_df<-tibble(P_card_v, CaMorR_v, DiMorR_v, P_dig_v)
variab_df
saveRDS(variab_df, "variab_df_dig.RDS")
```


```{r}
which.min(reps_SMSE)
min(reps_SMSE)
BestVariab<-variab_df[which.min(reps_SMSE),]
BestVariab
saveRDS(BestVariab, "BestVariab__dig_.RDS")
```


